export const COOKING_RESOURCE_LIST = {
  image: [
    ['touch-guide', 'common/image/touch-guide.png'],
    ['mute', 'common/image/mute.png'],
    ['unmute', 'common/image/unmute.png'],
    ['playBtn', 'common/image/play.png'],
    ['bg', 'cooking/image/bg.png'],
    ['buns', 'cooking/image/buns.png'],
    ['bun', 'cooking/image/bun.png'],
    ['bun-patty', 'cooking/image/bun-patty.png'],
    ['hotdog', 'cooking/image/hotdog.png'],
    ['hotdog-bun', 'cooking/image/hotdog-bun.png'],
    ['hotdog-buns', 'cooking/image/hotdog-buns.png'],
    ['buns-ketchup', 'cooking/image/buns-ketchup.png'],
    ['ketchup', 'cooking/image/ketchup.png'],
    ['buns-mustard', 'cooking/image/buns-mustard.png'],
    ['mustard', 'cooking/image/mustard.png'],
    ['grille', 'cooking/image/grille.png'],
    ['pan', 'cooking/image/pan.png'],
    ['trash-cans', 'cooking/image/trash-cans.png'],
    ['patty', 'cooking/image/patty.png'],
    ['patty-rare', 'cooking/image/patty-rare.png'],
    ['patty-burnt', 'cooking/image/patty-burnt.png'],
    ['sausage', 'cooking/image/sausage.png'],
    ['sausage-rare', 'cooking/image/sausage-rare.png'],
    ['sausage-burnt', 'cooking/image/sausage-burnt.png'],
    ['tomato', 'cooking/image/tomato.png'],
    ['lettuce', 'cooking/image/lettuce.png'],
    ['tray', 'cooking/image/tray.png'],
    ['buns-tray', 'cooking/image/buns-tray.png'],
    ['buns-up', 'cooking/image/buns-up.png'],
    ['buns-down', 'cooking/image/buns-down.png'],
    ['dispenser', 'cooking/image/dispenser.png'],
    ['drink', 'cooking/image/drink.png'],
    ['guest-menu', 'cooking/image/guest-menu.png'],
    ['customer-in', 'cooking/image/customer-in.png'],
    ['customer', 'cooking/image/customer.png'],
    ['customer-wait', 'cooking/image/customer-wait.png'],
  ],
  audio: [
    ['bgm', 'cooking/sound/bgm.mp3'],
    ['coin', 'cooking/sound/coin.mp3'],
    ['sizzle', 'cooking/sound/sizzle.mp3'],
    ['squeeze', 'cooking/sound/squeeze.mp3'],
    ['rustle', 'cooking/sound/rustle.mp3'],
  ],
} as const;
